baseURL = ""
languageCode = "en-us"
title = "Madhav Singhal"
disableKinds = ["section", "categories"]
disqusShortname = ""
pygmentsCodeFences = false
pygmentsUseClasses = false
paginate = 999
minify = true
googleAnalytics = "G-LE13RJ33EW"

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Author]
  name = "Madhav Singhal"

[params]
  description = "Madhav Singhal's Personal Website"
  author = "Madhav Singhal"
  copyright = "Madhav Singhal, 2023"
  logo = ""

[frontmatter]
  date  = [":filename", ":default"]
  author = ""
  github = ""
  facebook = ""
  og_image = ""
  sitename = ""
  twitter = "madhavsinghal_"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -20

  [[menu.main]]
    identifier = "bookshelf"
    name       = "Bookshelf"
    url        = "/bookshelf/"
    weight     = -10

  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = -5
